"""Rebuild the checked-in browser bundle: python -m pip install rjsmin==1.2.5."""
from pathlib import Path
from rjsmin import jsmin

ROOT = Path(__file__).resolve().parents[1]
SOURCES = [
    'assets/js/vendor/jquery/jquery-3.7.1.min.js',
    'assets/js/plugins/jquery.fitvids.js',
    'assets/js/plugins/jquery.greedy-navigation.js',
    'assets/js/plugins/jquery.magnific-popup.js',
    'assets/js/plugins/jquery.smooth-scroll.min.js',
    'assets/js/plugins/stickyfill.min.js',
    'assets/js/_main.js',
]

bundle = '/*! Generated by scripts/build_js.py; vendor license notices retained. */\n'
for name in SOURCES:
    bundle += jsmin((ROOT / name).read_text(encoding='utf-8'), keep_bang_comments=True) + ';\n'
(ROOT / 'assets/js/main.min.js').write_text(bundle, encoding='utf-8', newline='\n')
print('Rebuilt assets/js/main.min.js')
